# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'learningmathematicas'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Nivel Educativo
    submenu:
      - name: Infantil
        link: /projects/microbam
      - name: Primaria
        link: /projects/ourlegacy
  - name: Entradas
    link: /
  - name: Etiquetas
    link: /tags
  - name: Blog
    link: /about
  - name: Siguenos
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/AxelCotonGutierrez
     
    
