# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'learningmathematicas'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-K1CHGHX488'

menu: 
  - name: Infantil
    submenu:
      - name: Infantil
        link: /projects/Infantil
      - name: Matemáticas
        link: /projects/Infantil/MInfantil.html
      - name: Primaria
        link: /projects/ourlegacy
  - name: Nivel Educativo
    submenu:
      - name: Infantil
        link: /projects/Infantil
      - name: Infantil
        link: /projects/Primaria
  - name: Entradas
    link: /
  - name: Etiquetas
    link: /tags
  - name: Blog
    link: /about
  - name: Utilidades
    submenu:
      - name: Glosario
        link: https://axelcotongutierrez.github.io/GlosarioCT/
    
